project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: docs/_build/gettext/**/*.pot
    translation: docs/locale/%two_letters_code%/LC_MESSAGES/%original_path%/%file_name%.po
