name: Crowdin Action

on:
  push:
    branches: [ main ]

jobs:
  crowdin:
    name: "Synchronize Crowdin Localizations"
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Up Python 3.11
      uses: actions/setup-python@v4
      with:
          python-version: "3.11"
          cache: 'pip'

    - name: Upgrade Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[docs]

    - name: Make Localization for Docs
      working-directory: ./docs
      run: |
          make gettext

    - name: Crowdin Action
      uses: crowdin/github-action@1.5.1
      with:
        upload_translations: false
        download_translations: true
        export_only_approved: true
        push_translations: true
        commit_message: 'New Crowdin translations by Github Action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
